// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package seis.stthomas.edu.ai;

import org.springframework.beans.factory.annotation.Configurable;
import seis.stthomas.edu.ai.PieceMove;

privileged aspect PieceMove_Roo_Configurable {
    
    declare @type: PieceMove: @Configurable;
    
}
