// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package seis.stthomas.edu.domain;

import org.springframework.beans.factory.annotation.Configurable;
import seis.stthomas.edu.domain.BoardDataOnDemand;

privileged aspect BoardDataOnDemand_Roo_Configurable {
    
    declare @type: BoardDataOnDemand: @Configurable;
    
}
