// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package seis.stthomas.edu.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import seis.stthomas.edu.domain.Board;
import seis.stthomas.edu.domain.BoardDataOnDemand;
import seis.stthomas.edu.domain.Game;
import seis.stthomas.edu.domain.GameDataOnDemand;

privileged aspect BoardDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BoardDataOnDemand: @Component;
    
    private Random BoardDataOnDemand.rnd = new SecureRandom();
    
    private List<Board> BoardDataOnDemand.data;
    
    @Autowired
    private GameDataOnDemand BoardDataOnDemand.gameDataOnDemand;
    
    public Board BoardDataOnDemand.getNewTransientBoard(int index) {
        Board obj = new Board();
        setGame(obj, index);
        return obj;
    }
    
    public void BoardDataOnDemand.setGame(Board obj, int index) {
        Game game = gameDataOnDemand.getSpecificGame(index);
        obj.setGame(game);
    }
    
    public Board BoardDataOnDemand.getSpecificBoard(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Board obj = data.get(index);
        Long id = obj.getId();
        return Board.findBoard(id);
    }
    
    public Board BoardDataOnDemand.getRandomBoard() {
        init();
        Board obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Board.findBoard(id);
    }
    
    public boolean BoardDataOnDemand.modifyBoard(Board obj) {
        return false;
    }
    
    public void BoardDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Board.findBoardEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Board' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Board>();
        for (int i = 0; i < 10; i++) {
            Board obj = getNewTransientBoard(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
