// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package seis.stthomas.edu.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import seis.stthomas.edu.domain.Board;
import seis.stthomas.edu.domain.BoardDataOnDemand;
import seis.stthomas.edu.domain.King;
import seis.stthomas.edu.domain.KingDataOnDemand;

privileged aspect KingDataOnDemand_Roo_DataOnDemand {
    
    declare @type: KingDataOnDemand: @Component;
    
    private Random KingDataOnDemand.rnd = new SecureRandom();
    
    private List<King> KingDataOnDemand.data;
    
    @Autowired
    private BoardDataOnDemand KingDataOnDemand.boardDataOnDemand;
    
    public King KingDataOnDemand.getNewTransientKing(int index) {
        King obj = new King();
        setBoard(obj, index);
        setHasMoved(obj, index);
        setIsWhite(obj, index);
        setPieceValue(obj, index);
        return obj;
    }
    
    public void KingDataOnDemand.setBoard(King obj, int index) {
        Board board = boardDataOnDemand.getRandomBoard();
        obj.setBoard(board);
    }
    
    public void KingDataOnDemand.setHasMoved(King obj, int index) {
        Boolean hasMoved = true;
        obj.setHasMoved(hasMoved);
    }
    
    public void KingDataOnDemand.setIsWhite(King obj, int index) {
        Boolean isWhite = true;
        obj.setIsWhite(isWhite);
    }
    
    public void KingDataOnDemand.setPieceValue(King obj, int index) {
        int pieceValue = index;
        obj.setPieceValue(pieceValue);
    }
    
    public King KingDataOnDemand.getSpecificKing(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        King obj = data.get(index);
        Long id = obj.getId();
        return King.findKing(id);
    }
    
    public King KingDataOnDemand.getRandomKing() {
        init();
        King obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return King.findKing(id);
    }
    
    public boolean KingDataOnDemand.modifyKing(King obj) {
        return false;
    }
    
    public void KingDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = King.findKingEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'King' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<King>();
        for (int i = 0; i < 10; i++) {
            King obj = getNewTransientKing(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
