// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package seis.stthomas.edu.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import seis.stthomas.edu.domain.King;
import seis.stthomas.edu.domain.KingDataOnDemand;
import seis.stthomas.edu.domain.KingIntegrationTest;

privileged aspect KingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: KingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: KingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: KingIntegrationTest: @Transactional;
    
    @Autowired
    private KingDataOnDemand KingIntegrationTest.dod;
    
    @Test
    public void KingIntegrationTest.testCountKings() {
        Assert.assertNotNull("Data on demand for 'King' failed to initialize correctly", dod.getRandomKing());
        long count = King.countKings();
        Assert.assertTrue("Counter for 'King' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void KingIntegrationTest.testFindKing() {
        King obj = dod.getRandomKing();
        Assert.assertNotNull("Data on demand for 'King' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'King' failed to provide an identifier", id);
        obj = King.findKing(id);
        Assert.assertNotNull("Find method for 'King' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'King' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void KingIntegrationTest.testFindAllKings() {
        Assert.assertNotNull("Data on demand for 'King' failed to initialize correctly", dod.getRandomKing());
        long count = King.countKings();
        Assert.assertTrue("Too expensive to perform a find all test for 'King', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<King> result = King.findAllKings();
        Assert.assertNotNull("Find all method for 'King' illegally returned null", result);
        Assert.assertTrue("Find all method for 'King' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void KingIntegrationTest.testFindKingEntries() {
        Assert.assertNotNull("Data on demand for 'King' failed to initialize correctly", dod.getRandomKing());
        long count = King.countKings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<King> result = King.findKingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'King' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'King' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void KingIntegrationTest.testFlush() {
        King obj = dod.getRandomKing();
        Assert.assertNotNull("Data on demand for 'King' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'King' failed to provide an identifier", id);
        obj = King.findKing(id);
        Assert.assertNotNull("Find method for 'King' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyKing(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'King' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KingIntegrationTest.testMergeUpdate() {
        King obj = dod.getRandomKing();
        Assert.assertNotNull("Data on demand for 'King' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'King' failed to provide an identifier", id);
        obj = King.findKing(id);
        boolean modified =  dod.modifyKing(obj);
        Integer currentVersion = obj.getVersion();
        King merged = (King)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'King' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KingIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'King' failed to initialize correctly", dod.getRandomKing());
        King obj = dod.getNewTransientKing(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'King' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'King' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'King' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void KingIntegrationTest.testRemove() {
        King obj = dod.getRandomKing();
        Assert.assertNotNull("Data on demand for 'King' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'King' failed to provide an identifier", id);
        obj = King.findKing(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'King' with identifier '" + id + "'", King.findKing(id));
    }
    
}
