// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package seis.stthomas.edu.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import seis.stthomas.edu.domain.Board;
import seis.stthomas.edu.domain.BoardDataOnDemand;
import seis.stthomas.edu.domain.Knight;
import seis.stthomas.edu.domain.KnightDataOnDemand;

privileged aspect KnightDataOnDemand_Roo_DataOnDemand {
    
    declare @type: KnightDataOnDemand: @Component;
    
    private Random KnightDataOnDemand.rnd = new SecureRandom();
    
    private List<Knight> KnightDataOnDemand.data;
    
    @Autowired
    private BoardDataOnDemand KnightDataOnDemand.boardDataOnDemand;
    
    public Knight KnightDataOnDemand.getNewTransientKnight(int index) {
        Knight obj = new Knight();
        setBoard(obj, index);
        setHasMoved(obj, index);
        setIsWhite(obj, index);
        setPieceValue(obj, index);
        return obj;
    }
    
    public void KnightDataOnDemand.setBoard(Knight obj, int index) {
        Board board = boardDataOnDemand.getRandomBoard();
        obj.setBoard(board);
    }
    
    public void KnightDataOnDemand.setHasMoved(Knight obj, int index) {
        Boolean hasMoved = true;
        obj.setHasMoved(hasMoved);
    }
    
    public void KnightDataOnDemand.setIsWhite(Knight obj, int index) {
        Boolean isWhite = true;
        obj.setIsWhite(isWhite);
    }
    
    public void KnightDataOnDemand.setPieceValue(Knight obj, int index) {
        int pieceValue = index;
        obj.setPieceValue(pieceValue);
    }
    
    public Knight KnightDataOnDemand.getSpecificKnight(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Knight obj = data.get(index);
        Long id = obj.getId();
        return Knight.findKnight(id);
    }
    
    public Knight KnightDataOnDemand.getRandomKnight() {
        init();
        Knight obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Knight.findKnight(id);
    }
    
    public boolean KnightDataOnDemand.modifyKnight(Knight obj) {
        return false;
    }
    
    public void KnightDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Knight.findKnightEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Knight' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Knight>();
        for (int i = 0; i < 10; i++) {
            Knight obj = getNewTransientKnight(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
