// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package seis.stthomas.edu.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import seis.stthomas.edu.domain.Board;
import seis.stthomas.edu.domain.BoardDataOnDemand;
import seis.stthomas.edu.domain.Queen;
import seis.stthomas.edu.domain.QueenDataOnDemand;

privileged aspect QueenDataOnDemand_Roo_DataOnDemand {
    
    declare @type: QueenDataOnDemand: @Component;
    
    private Random QueenDataOnDemand.rnd = new SecureRandom();
    
    private List<Queen> QueenDataOnDemand.data;
    
    @Autowired
    private BoardDataOnDemand QueenDataOnDemand.boardDataOnDemand;
    
    public Queen QueenDataOnDemand.getNewTransientQueen(int index) {
        Queen obj = new Queen();
        setBoard(obj, index);
        setHasMoved(obj, index);
        setIsWhite(obj, index);
        setPieceValue(obj, index);
        return obj;
    }
    
    public void QueenDataOnDemand.setBoard(Queen obj, int index) {
        Board board = boardDataOnDemand.getRandomBoard();
        obj.setBoard(board);
    }
    
    public void QueenDataOnDemand.setHasMoved(Queen obj, int index) {
        Boolean hasMoved = true;
        obj.setHasMoved(hasMoved);
    }
    
    public void QueenDataOnDemand.setIsWhite(Queen obj, int index) {
        Boolean isWhite = true;
        obj.setIsWhite(isWhite);
    }
    
    public void QueenDataOnDemand.setPieceValue(Queen obj, int index) {
        int pieceValue = index;
        obj.setPieceValue(pieceValue);
    }
    
    public Queen QueenDataOnDemand.getSpecificQueen(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Queen obj = data.get(index);
        Long id = obj.getId();
        return Queen.findQueen(id);
    }
    
    public Queen QueenDataOnDemand.getRandomQueen() {
        init();
        Queen obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Queen.findQueen(id);
    }
    
    public boolean QueenDataOnDemand.modifyQueen(Queen obj) {
        return false;
    }
    
    public void QueenDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Queen.findQueenEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Queen' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Queen>();
        for (int i = 0; i < 10; i++) {
            Queen obj = getNewTransientQueen(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
