// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package seis.stthomas.edu.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import seis.stthomas.edu.domain.Rook;
import seis.stthomas.edu.domain.RookDataOnDemand;
import seis.stthomas.edu.domain.RookIntegrationTest;

privileged aspect RookIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RookIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RookIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RookIntegrationTest: @Transactional;
    
    @Autowired
    private RookDataOnDemand RookIntegrationTest.dod;
    
    @Test
    public void RookIntegrationTest.testCountRooks() {
        Assert.assertNotNull("Data on demand for 'Rook' failed to initialize correctly", dod.getRandomRook());
        long count = Rook.countRooks();
        Assert.assertTrue("Counter for 'Rook' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RookIntegrationTest.testFindRook() {
        Rook obj = dod.getRandomRook();
        Assert.assertNotNull("Data on demand for 'Rook' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rook' failed to provide an identifier", id);
        obj = Rook.findRook(id);
        Assert.assertNotNull("Find method for 'Rook' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Rook' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RookIntegrationTest.testFindAllRooks() {
        Assert.assertNotNull("Data on demand for 'Rook' failed to initialize correctly", dod.getRandomRook());
        long count = Rook.countRooks();
        Assert.assertTrue("Too expensive to perform a find all test for 'Rook', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Rook> result = Rook.findAllRooks();
        Assert.assertNotNull("Find all method for 'Rook' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Rook' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RookIntegrationTest.testFindRookEntries() {
        Assert.assertNotNull("Data on demand for 'Rook' failed to initialize correctly", dod.getRandomRook());
        long count = Rook.countRooks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Rook> result = Rook.findRookEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Rook' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Rook' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RookIntegrationTest.testFlush() {
        Rook obj = dod.getRandomRook();
        Assert.assertNotNull("Data on demand for 'Rook' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rook' failed to provide an identifier", id);
        obj = Rook.findRook(id);
        Assert.assertNotNull("Find method for 'Rook' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRook(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Rook' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RookIntegrationTest.testMergeUpdate() {
        Rook obj = dod.getRandomRook();
        Assert.assertNotNull("Data on demand for 'Rook' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rook' failed to provide an identifier", id);
        obj = Rook.findRook(id);
        boolean modified =  dod.modifyRook(obj);
        Integer currentVersion = obj.getVersion();
        Rook merged = (Rook)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Rook' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RookIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Rook' failed to initialize correctly", dod.getRandomRook());
        Rook obj = dod.getNewTransientRook(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Rook' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Rook' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Rook' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RookIntegrationTest.testRemove() {
        Rook obj = dod.getRandomRook();
        Assert.assertNotNull("Data on demand for 'Rook' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rook' failed to provide an identifier", id);
        obj = Rook.findRook(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Rook' with identifier '" + id + "'", Rook.findRook(id));
    }
    
}
