// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package seis.stthomas.edu.domain;

import javax.persistence.Entity;
import seis.stthomas.edu.domain.Pawn;

privileged aspect Pawn_Roo_Jpa_Entity {
    
    declare @type: Pawn: @Entity;
    
    public Pawn.new() {
        super();
    }

}
